baseURL = 'https://jonsnowseven.github.io/'
languageCode = 'en-us'
title = ''
theme = "color-your-world"
# googleAnalytics = "..."
enableRobotsTXT = true

[pagination]
pagerSize = 100

[markup.goldmark.renderer]
unsafe = true

[params]

# Site description
description = "João Neves's personal website"

# Author
[params.author]
name = "João Neves"
email = "joaojdneves@gmail.com"

[params.style]
# Dark mode as default
# User preferences (site/system settings) will still have priority over it
# The default is false
isDark = true
# Accent colors for dark and light mode respectively
darkAccent = "#ffd700"  # Default is "#1dbc91"
lightAccent = "#808000" # Default is "#1f676b" 
# More colors, pick as many as you want (not really sure if there's a limit)
# Apparently these may not show up on every modern browser (ie.: Firefox)
# There's no default value. Used here just as example
presets = ["#ffd700"]

[params.social.centralized]
github = ["jonsnowseven"]
linkedin = ["jonsnow7"]
x = ["@7_snow_storm"]
stackOverflow = [ "j-snow" ]
#entry         = [ "username", "label (optional)" ]

# The "entry" here IS important. It's used to load the data.

[params.social.decentralized]
# The "entry" here ISN'T important. It's used for nothing.

[menu]
[[menu.main]]
name = "Home"
weight = 1
url = "/"
[[menu.main]]
name = "Blog"
weight = 2
url = "blog/"
[[menu.main]]
name = "CV"
weight = 3
url = "cv"
