baseURL = "https://jonsnowseven.github.io/"
languageCode = 'en-us'
title = 'João Neves'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

[params]
  home = "content/_index.md"
